

# -----------
# Constantes
# -----------

CAR_LENGTH = 100 #1 metro
delta_t = 0.02
GRAVEDAD = 9.8
FACTOR_MULTIPLICADOR_LONGITUD = 1
RELACION_PIXELS = 100 #CADA PIXEL ES 1cm POR LO QUE TENGO QUE DIVIDIR POR ESTE FACTOR
